version: '3.8'

networks:
  ChatGPT-project-network:
    driver: bridge

services:
  app:
    image: 'chat-gpt-project'
    container_name: chat-gpt-project-container
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - postgres
      - redis
    environment:
      - OPEN_AI_KEY=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
      - POSTGRES_PASSWORD=Din5675671
    networks:
      - ChatGPT-project-network

  postgres:
    image: 'postgres'
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=Din5675671
      - PGUSER=postgres
    networks:
      - ChatGPT-project-network


  redis:
    image: 'redis'
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - ChatGPT-project-network
